DROP TABLE IF EXISTS BOOK;

CREATE TABLE BOOK(
ISBN VARCHAR2(256) NOT NULL,
TITLE VARCHAR2(256) NOT NULL,
AUTHOR VARCHAR2(256) NOT NULL,
CREATION_TIME TIMESTAMP NOT NULL,
LAST_EDIT_TIME TIMESTAMP NOT NULL
);

ALTER TABLE BOOK ADD CONSTRAINT PK_BOOK_ISBN PRIMARY KEY (ISBN);

DROP TABLE IF EXISTS BOOK_COLLECTION;

CREATE TABLE BOOK_COLLECTION(
BOOK_COLLECTION_ID BIGINT NOT NULL,
NAME VARCHAR2(256) NOT NULL,
CREATION_TIME TIMESTAMP NOT NULL,
LAST_EDIT_TIME TIMESTAMP NOT NULL
);

ALTER TABLE BOOK_COLLECTION ADD CONSTRAINT PK_BOOK_COLLECTION_ID PRIMARY KEY (BOOK_COLLECTION_ID);
ALTER TABLE BOOK_COLLECTION ADD CONSTRAINT UK_BOOK_COLLECTION_NAME UNIQUE (NAME);

DROP TABLE IF EXISTS BOOK_COLLECTION_LINK;

CREATE TABLE BOOK_COLLECTION_LINK(
BOOK_COLLECTION_ID BIGINT NOT NULL,
ISBN VARCHAR2(256) NOT NULL
);

ALTER TABLE BOOK_COLLECTION_LINK ADD CONSTRAINT PK_BOOK_COLLECTION_LINK PRIMARY KEY(BOOK_COLLECTION_ID, ISBN);
ALTER TABLE BOOK_COLLECTION_LINK ADD CONSTRAINT FK_BCL_BOOK FOREIGN KEY(ISBN) REFERENCES BOOK(ISBN);
ALTER TABLE BOOK_COLLECTION_LINK ADD CONSTRAINT FK_BCL_BOOK_COLLECTION FOREIGN KEY(BOOK_COLLECTION_ID) REFERENCES BOOK_COLLECTION(BOOK_COLLECTION_ID);
CREATE INDEX FK_BCL_BOOK ON BOOK_COLLECTION_LINK(ISBN);
CREATE INDEX FK_BCL_BOOK_COLLECTION ON BOOK_COLLECTION_LINK(BOOK_COLLECTION_ID);

CREATE SEQUENCE BOOK_COLLECTION_ID_SEQ START WITH 1 INCREMENT BY 1;