DROP TABLE IF EXISTS BOOK;

CREATE TABLE BOOK(
ISBN BIGINT NOT NULL,
TITLE VARCHAR2(256) NOT NULL,
AUTHOR VARCHAR2(256) NOT NULL,
CREATION_TIME TIMESTAMP NOT NULL,
LAST_EDIT_TIME TIMESTAMP NOT NULL
);

ALTER TABLE BOOK ADD CONSTRAINT PK_BOOK_ISBN PRIMARY KEY (ISBN);